# Generated by Django 3.0.8 on 2020-08-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='CFF', max_length=100),
        ),
    ]
