# Generated by Django 3.0.8 on 2020-08-04 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_Number', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default=orders.models.increment_order_id, editable=False, max_length=20, null=True)),
                ('delivery_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.IntegerField(choices=[(0, 'Not Paid'), (2, 'Partial Paid'), (1, 'Paid')], default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderitems', to='orders.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.Product')),
            ],
        ),
    ]
