# Generated by Django 3.0.8 on 2020-08-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='desc',
            new_name='description',
        ),
    ]
