# Generated by Django 3.0.8 on 2020-08-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200804_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
