# Generated by Django 3.0.8 on 2020-08-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200812_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
